# .github/workflows/main.yml

name: Java CI/CD to EC2

# ✅ [수정] main 브랜치에 push 또는 pull request가 발생했을 때 실행
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  CONTAINER_NAME: my-app-container

jobs:
  build-push-and-deploy:
    # pull_request 이벤트 중에는 배포하지 않도록 조건 추가 (push 시에만 배포)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "${{ secrets.ENV_FILE }}" > .env
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            export DOCKER_IMAGE=${{ steps.meta.outputs.tags }}
            docker-compose -f docker-compose.yml pull highlight-backend
            docker-compose -f docker-compose.yml up -d --remove-orphans